title: Chunwei Ma
position: Ph.D. in Computer Science
affiliation: The State University of New York at Buffalo
email: chunweim (at) buffalo.edu
keywords: chunwei ma, ma chunwei, chunweima, machunwei
google_scholar: https://scholar.google.com/citations?user=4NOrXN8AAAAJ&hl=en
github_link: https://github.com/horsepurve
linkedin: https://www.linkedin.com/in/chunwei-ma-602548122/
avatar: ./assets/img/avatar.png
google_analytics: G-JV25SSSZ5D
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Chunwei Ma is a Ph.D. candidate in Computer Science at The State University of New York at Buffalo, working with Prof. Jinhui Xu. His research lies at the intersection of deep learning and computational geometry.
canonical: https://MaChunwei.github.io
remote_theme: yaoyao-liu/minimal-light
